### ISSUE TITLE
Applikation

### ISSUE THREAD

**Issue by mf222nb** [CCHolmgren/ch222kv_1dv450_kod#1]
Hej!

Jag har tittat igenom din applikations kod och den är väldigt bra strukturerad och bra att det finns kommentarer ovanför metoderna som säger vilken url de använder. Roligt att du har gjort så man kan få det i json format med.

Hade gärna sett en installationsanvisning så att man visste exakt vad man skulle göra.
En sak som jag inte kan göra är att testköra applikationen då jag får en röd sida när jag startar servern och går till localhost:3000, detta kan du gärna titta på så att jag kan testköra den med för är säkert något jag missat då jag inte hittar några installationsanvisningar men annars är koden väldigt bra skriven.

**Comment by fjohansson92** [comment]
Vet inte vad du får för fel men prova detta:
1. Lägg till gem    'coffee-script-source', '1.8.0'   i gemfile.
2. bundle install
3. bundle update coffee-script-source
4. rake db:setup
5. rails s

**Comment by ch222kv** [comment]
Har du följt instruktionerna som finns till Releasen? 

What you need to do to get it up and running:
1. Clone the repo.
2. Run a bundle install incase that you haven't got all gems installed.
3. Run rake db:setup to setup the database.
4. Run rake db:seed to create the administrator.
5. Run rails s or rails server incase you want to write more.
6. Login with admin and password which is an administrator who can remove api applications and users, or create a new user. 
7. Do your testing.

**Comment by mf222nb** [comment]
Fick igång applikationen efter lite strul med att avinstallera gems och installera om dem och uppdatera så det var lite krångligare för mig att få igång det än vad instruktionerna angav man skulle göra för att få igång den.
