### ISSUE TITLE
Issue sudo  apt-get install postgresql-9.4 

### ISSUE THREAD

**Issue by Grenmyr** [CCHolmgren/ch222kv_1dv450_kod#10]
Din installationsguide för linux är för ospecifierad för en novis som mig. Jag är dålig på setta upp saker, jag följde din linux länk. http://www.postgresql.org/download/linux/ubuntu/

Skriv en installationsgude istället för bara länka till oficiell dokumentattion. Din länk gav script om hur installera light versionen, dvs utan -dev.

För få igång postgresql var jag tvungen att köra sudo  apt-get install postgresql-server-dev-9.4 och det kom jag på genom googla runt.

**Comment by ch222kv** [comment]
Vilken version av vilken distro av Linux använder du? Ubuntu, Debian eller någon av de andra distron som finns listade på http://www.postgresql.org/download/linux/?

**Comment by Grenmyr** [comment]
3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
version 14.04

**Comment by ch222kv** [comment]
Ändrade tillbaka till sqlite.
