### ISSUE TITLE
Problem postgresql username och password

### ISSUE THREAD

**Issue by Grenmyr** [CCHolmgren/ch222kv_1dv450_kod#11]
Jag kunde inte fatta hur man reggar utvecklingskonto för rättigheter mot din Username:Rails profil som du kör databasen mot. 

FATAL:  Peer authentication failed for user "Rails"

Detta behövs inkluderas en guide i din installationsmanual. Jag löste problemet genom fråga klasskamrater. De fick ej heller igång det, då tog jag och klistrade in din https://github.com/ch222kv/ch222kv_1dv450_kod/commit/a93f44f37f3872c2f625bb9646c7aad24d0f4ba8#diff-efd648c48ec012ed2bc060d7326cad36 commit i database.yml filen och kör på sql lite istället.

Då kan jag köra rake db:setup och det funkar.

**Comment by ch222kv** [comment]
Ändrade tillbaka till sqlite.
