### ISSUE TITLE
Har du glömt pusha ditt angular projekt?

### ISSUE THREAD

**Issue by Grenmyr** [CCHolmgren/ch222kv_1dv450_kod#12]
Hittar inga av dessa resurser i ditt repo från github. 
Ifrån din another.html.erb fil som finns i app/views/layouts länkar du in dessa resurser. Jag hittar inga av dom i ditt repo.

```
<script src="assets/javascripts/main.js"></script>

<script src="assets/javascripts/angular/services/EventService.js"></script>
<script src="assets/javascripts/angular/services/TagService.js"></script>
<script src="assets/javascripts/angular/services/ResourceService.js"></script>
<script src="assets/javascripts/angular/controllers/EventListCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/EventEditCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/EventSearchCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/EventCreateCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/EventDetailCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/TagListCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/LoginCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/LogoutCtrl.js"></script>
<script src="assets/javascripts/angular/controllers/MenuCtrl.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>"
```

**Comment by ch222kv** [comment]
Som du ser så finns de i assets/javascripts/angular. Rails serverar filerna som befinner sig i public mappen utan att göra något med dem, https://github.com/ch222kv/ch222kv_1dv450_kod/tree/master/RegistrationApplication/public. Där finns allting som har med angular att göra.

**Comment by Grenmyr** [comment]
Ahaa, så dem scriptinlänkarna det e typ gammal dökod då eller?
Ok gutt då går jag till den andra mappen.

**Comment by ch222kv** [comment]
Allt som placeras i public mappen blir tillgängligt under samma mappstruktur, bara att public inte ska vara med. Så assets/ ligger under public/assets/ osv.

**Comment by ch222kv** [comment]
Ändrade tillbaka till sqlite.
