### ISSUE TITLE
Api index bug

### ISSUE THREAD

**Issue by fjohansson92** [CCHolmgren/ch222kv_1dv450_kod#2]
Om man loggar in som en användare som inte är admin och försöker registrera en API-nyckel får man ett fel. Problemet uppstår på rad 14 i api_applications/index.html.erb där man försöker loopa @api_applications som är nil. Problemet rättas lätt till genom att ändra rad 3 i samma fil från:
if @api_applications != [] till if @api_applications .

**Comment by 1dv450** [comment]
:+1:
