### ISSUE TITLE
Övrigt

### ISSUE THREAD

**Issue by fjohansson92** [CCHolmgren/ch222kv_1dv450_kod#6]
Lista med små saker som jag tycker du borde göra:
- kolla över länkar så texten stämmer
- ta bort länkar man inte behöver se som tex ta bort användare när man inte är inloggad
- kolla över meddelanden så man inte får flera likadana, eller i fel färger
- lägg till en felsida
- styla lite
- pagination på listorna med nycklar och användare
- lägga ut login_post och logout_post i en egen controller

Positivt:
- bra med CRUD funktionalitet för user och api
- går att registrera flera applikationer till ett konto
- bara att fixa några buggar så uppfyller du kraven. Lycka till!

**Comment by mf222nb** [comment]
Fick igång min applikation och jag håller med vad fjohansson92 säger med saker som borde göras som att lägga till felsida, kolla över felmeddelandena etc. 

Som han med säger är det riktigt bra att man kan registrera flera applikationer på ett konto och att man har mycket CRUD funktionalitet för user och api. Han har även tagit upp buggar i andra issues som borde fixas så jag lägger inte upp nya issues om dem.
